name: ci

on:
  pull_request:
  push:

jobs:
  Build:
    strategy:
      matrix:
        go-version: [stable, oldstable]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build .
      - run: ./gotestsum -f testname -- ./... -race -count=1
